version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python -m unittest discover tests
  
  build:
    commands:
      - sam build
      - cd .aws-sam/build
      - aws cloudformation package
        --template template.yml
        --s3-bucket $S3_BUCKET
        --output-template template-export.yml
artifacts:
  files:
    - .aws-sam/build/template-export.yml